name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # Déclenche l'action lors d'un push sur la branche 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Utilisation de l'environnement Ubuntu pour exécuter les jobs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Récupère le code source de votre dépôt

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1  # Connexion à Azure Container Registry
      with:
        username: ${{ secrets.AZURE_USERNAME }}
        password: ${{ secrets.AZURE_PASSWORD }}
    
    - name: Build and Push Docker Image
      run: |
        docker build -t my-app:${{ github.sha }} .  # Construit l'image Docker
        docker tag my-app:${{ github.sha }} myregistry.azurecr.io/my-app:${{ github.sha }}  # Tag l'image avec ACR
        docker push myregistry.azurecr.io/my-app:${{ github.sha }}  # Pousse l'image vers ACR
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2  # Déploie l'image Docker sur Azure Web App
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}  # Nom de votre application Azure
        images: myregistry.azurecr.io/my-app:${{ github.sha }}  # L'image Docker à déployer
